# Generated by Django 4.0.6 on 2022-07-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_link_options_link_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_url',
        ),
        migrations.AddField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
