# Generated by Django 4.0.6 on 2022-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
