# Generated by Django 4.0.6 on 2022-07-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_link_long_url_alter_link_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created_at'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
